# Generated by Django 2.0.5 on 2018-05-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='count_unique_words',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
